### ISSUE TITLE
 Accessing 'template' in <web@component:async-button::ember472> is deprecated.

### ISSUE THREAD

**Issue by chrismllr** [dockyard/ember-cli-async-button#59]
I'm getting this deprecation log in reference to async-button...

```
DEPRECATION: Accessing 'template' in <web@component:async-button::ember472> is deprecated. To determine if a block was specified to <web@component:async-button::ember472> please use '{{#if hasBlock}}' in the components layout.
        at HANDLERS.(anonymous function) (http://localhost:4201/assets/vendor.js:72821:7)
        at raiseOnDeprecation (http://localhost:4201/assets/vendor.js:72907:7)
        at HANDLERS.(anonymous function) (http://localhost:4201/assets/vendor.js:72821:7)
        at handleDeprecationWorkflow (http://localhost:4201/assets/vendor.js:72956:9)
        at HANDLERS.(anonymous function) (http://localhost:4201/assets/vendor.js:72821:7)
        at deprecationCollector (http://localhost:4201/assets/vendor.js:72978:5)
        at HANDLERS.(anonymous function) (http://localhost:4201/assets/vendor.js:72821:7)
        at invoke (http://localhost:4201/assets/vendor.js:72833:7)
        at Object.deprecate (http://localhost:4201/assets/vendor.js:72912:5)
```

Is this due to my usage, or something within the addon?
thanks!

**Comment by danmcclain** [comment]
If you use the master branch, that deprecation is resolved. We have a release pending

**Comment by chrismllr** [comment]
Great, thanks!
